= Development: Bucket Reconciliation

This page gives a brief overview how `Buckets` are managed in the provider.

Note that these diagrams are on a high-level and don't visualize the path for every possible situation.

== Creating Buckets

image::bucket-create.drawio.svg[]

- All bucket operations are done using any S3-compatible client library.

== Updating Buckets

image::bucket-update.drawio.svg[]

- Since renaming buckets and changing region is not possible, there's nothing to update once the bucket exists.
- Immutable fields are going through the validating webhook server first.
  This prevents changing the spec once the bucket exists.

== Deleting Buckets

image::bucket-delete.drawio.svg[]

- Deleting bucket is a synchronous operation.
- Due to https://github.com/vshn/provider-cloudscale/issues/24[a certain race condition with deleting ObjectsUsers] there's no attempt to observe the bucket in the second reconiliation, if the bucket was successfully deleted in the first reconciliation.
