= Development: ObjectsUser Reconciliation

This page gives a brief overview how `ObjectsUsers` are managed in the provider.

Note that these diagrams are on a high-level and don't visualize the path for every possible situation.

== Creating ObjectsUsers

image::objectsuser-create.drawio.svg[]

- In cloudscale.ch API, display names are not unique, there can be multiple users with different user IDs that share the same display name.
- During the first reconciliation we do not check if an objects user with the desired display name exists, since we don't know the objects user ID.
- After the first reconciliation, the user ID, as generated by the cloudscale.ch API, is stored in the status.

== Updating ObjectsUsers

image::objectsuser-update.drawio.svg[]

- Tags and display name can be updated, since the actual user ID is stored in the status.

== Deleting ObjectsUsers

image::objectsuser-delete.drawio.svg[]

- cloudscale.ch API prevents deleting an objects user if there are buckets still attached in any region.
- If the user cannot be deleted in cloudscale.ch API, the resource remains in a "deletion pending" state.
- The credentials `Secret` is garbage collected after the resource is actually gone.
