= Getting Started

This page describes how to create a new S3 bucket after you have installed the operator.

== Prerequisites

* `kubectl`
* Already running Kubernetes cluster
* Installed Operator (as a Crossplane Provider)
* An API token for cloudscale.ch with write permissions

== Steps

. Export your API token
+
[source,bash]
----
export CLOUDSCALE_API_TOKEN=<the-token>
----

. Create a `Secret` with the token
+
[source,yaml]
----
kubectl apply -f - <<EOF
include::example$api-token-secret.yaml[]
EOF
----

. Create a `ProviderConfig`
+
[source,yaml]
----
kubectl apply -f - <<EOF
include::example$cloudscale_providerconfig.yaml[]
EOF
----

. Create a file with the spec
+
[source,yaml]
----
cat - > objectsuser.yaml <<EOF
include::example$cloudscale_objectsuser.yaml[]
EOF
----

. Apply the spec in the cluster
+
[source,bash]
----
kubectl apply -f objectsuser.yaml
----

. Wait until the operator has provisioned the user
+
[source,bash]
----
kubectl wait --for condition=Ready objectsuser/my-cloudscale-user
----
+
[NOTE]
====
If you already have a `Secret` named `my-cloudscale-user-credentials`, it will get overwritten.
Set `spec.writeConnectionSecretToRef.name` to another name.
====

. Inspect the credential `Secret`
+
[source,bash]
----
kubectl get secret my-cloudscale-user-credentials -o yaml
----

. _(Optional):_ Change the spec.
  You can edit `objectsuser.yaml` to modify tags or change the displayname before applying the manifest again.
  The provider should update the objects user on cloudscale.ch as a consequence.
