apiVersion: cloudscale.crossplane.io/v1
kind: Bucket
metadata:
  creationTimestamp: null
  name: bucket
spec:
  forProvider:
    bucketDeletionPolicy: DeleteAll
    bucketName: my-provider-test-bucket
    credentialsSecretRef:
      name: my-cloudscale-user-credentials
      namespace: default
    endpointURL: objects.rma.cloudscale.ch
    region: rma
status:
  atProvider: {}
