package v1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// ObjectsUserStatus represents the observed state of a ObjectsUser.
type ObjectsUserStatus struct {
	Conditions []metav1.Condition `json:"conditions,omitempty"`
	// UserID is the unique ID as generated by cloudscale.ch.
	UserID string `json:"userID,omitempty"`
}

// GetConditions implements conditions.ObjectWithConditions.
func (in *ObjectsUser) GetConditions() []metav1.Condition {
	return in.Status.Conditions
}

// SetConditions implements conditions.ObjectWithConditions.
func (in *ObjectsUser) SetConditions(v []metav1.Condition) {
	in.Status.Conditions = v
}
